added name
sds270-s22/git-demo pull request #16
Opened 2022-02-01 19:18 UTC by kbruncati

2022-02-02 13:57 UTC, beanumber requested changes

2022-02-02 13:57 UTC, beanumber commented on README.md
> +ben bruncati
Could you please add a `-` so this becomes a list item?

Also, please make your name into a link that goes to that URL. The URL should not be visible.

2022-02-03 19:38 UTC, mariumtapal requested changes
Could you add a space between the `-` and your name? Looks great otherwise!

2022-02-03 22:25 UTC, mariumtapal approved these changes

2022-02-03 22:26 UTC, merged