Swaha
sds270-s22/git-demo pull request #2
Opened 2022-02-01 16:51 UTC by Swaha294

pull request - swaha

2022-02-01 17:53 UTC, beanumber requested changes

2022-02-01 17:53 UTC, beanumber commented on README.md
> +Swaha Bhattacharya - https://github.com/Swaha294
Could you please add a `-` so this becomes a list item?

2022-02-01 17:53 UTC, beanumber commented on README.md
> +Swaha Bhattacharya - https://github.com/Swaha294
Also, please make your name into a link that goes to that URL. The URL should not be visible.

2022-02-03 19:35 UTC, mariumtapal approved these changes

2022-02-03 19:35 UTC, merged