Alejandra
sds270-s22/git-demo pull request #21
Opened 2022-02-02 21:55 UTC by alejanmg

2022-02-03 00:28 UTC, beanumber requested changes

2022-02-03 00:28 UTC, beanumber commented on README.md
> +alejandra munoz garcia
Could you please add a `-` so this becomes a list item?

2022-02-03 00:28 UTC, beanumber commented on README.md
> +https://github.com/alejanmg
Also, please make your name into a link that goes to that URL. The URL should not be visible.

2022-02-04 19:35 UTC, beanumber commented on README.md
> +https://github.com/alejanmg
@alejanmg have you had a chance to look at this again?

2022-02-05 19:42 UTC, mariumtapal requested changes
The dash needs to be outside the square bracket with a space between the two in order to make it a list item! Could you make this change?

2022-02-05 21:53 UTC, mariumtapal approved these changes

2022-02-05 21:53 UTC, merged